// Auto-generated by scripts/generate-command-registry.ts
// Do not edit manually. Re-generate with: npm run generate:commands
window.EISCP_COMMANDS = [
  {
    "code": "PWR",
    "name": "system-power",
    "description": "System Power Command",
    "category": "Power / Mute",
    "actionType": "toggle",
    "values": [
      {
        "param": "00",
        "name": "standby"
      },
      {
        "param": "01",
        "name": "on"
      },
      {
        "param": "ALL",
        "name": "standby-all"
      }
    ],
    "hasQuery": true,
    "hasUpDown": false,
    "onValue": "01",
    "offValue": "00"
  },
  {
    "code": "AMT",
    "name": "audio-muting",
    "description": "Audio Muting Command",
    "category": "Power / Mute",
    "actionType": "toggle",
    "values": [
      {
        "param": "00",
        "name": "off"
      },
      {
        "param": "01",
        "name": "on"
      },
      {
        "param": "TG",
        "name": "toggle"
      }
    ],
    "hasQuery": true,
    "hasUpDown": false,
    "onValue": "01",
    "offValue": "00",
    "toggleValue": "TG"
  },
  {
    "code": "MVL",
    "name": "master-volume",
    "description": "Master Volume Command",
    "category": "Volume",
    "actionType": "stepper",
    "values": [
      {
        "param": "UP",
        "name": "level-up"
      },
      {
        "param": "DOWN",
        "name": "level-down"
      },
      {
        "param": "UP1",
        "name": "level-up-1db-step"
      },
      {
        "param": "DOWN1",
        "name": "level-down-1db-step"
      }
    ],
    "hasQuery": true,
    "hasUpDown": true
  },
  {
    "code": "SLI",
    "name": "input-selector",
    "description": "Input Selector Command",
    "category": "Input / Mode",
    "actionType": "selector",
    "values": [
      {
        "param": "08",
        "name": "8"
      },
      {
        "param": "09",
        "name": "9"
      },
      {
        "param": "10",
        "name": "dvd"
      },
      {
        "param": "11",
        "name": "strm-box"
      },
      {
        "param": "12",
        "name": "tv"
      },
      {
        "param": "20",
        "name": "tape-1"
      },
      {
        "param": "21",
        "name": "tape2"
      },
      {
        "param": "22",
        "name": "phono"
      },
      {
        "param": "23",
        "name": "cd"
      },
      {
        "param": "24",
        "name": "fm"
      },
      {
        "param": "25",
        "name": "am"
      },
      {
        "param": "26",
        "name": "tuner"
      },
      {
        "param": "27",
        "name": "music-server"
      },
      {
        "param": "28",
        "name": "internet-radio"
      },
      {
        "param": "29",
        "name": "usb"
      },
      {
        "param": "30",
        "name": "multi-ch"
      },
      {
        "param": "31",
        "name": "xm"
      },
      {
        "param": "32",
        "name": "sirius"
      },
      {
        "param": "33",
        "name": "dab"
      },
      {
        "param": "40",
        "name": "universal-port"
      },
      {
        "param": "41",
        "name": "line"
      },
      {
        "param": "42",
        "name": "line2"
      },
      {
        "param": "44",
        "name": "optical"
      },
      {
        "param": "45",
        "name": "coaxial"
      },
      {
        "param": "55",
        "name": "hdmi-5"
      },
      {
        "param": "56",
        "name": "hdmi-6"
      },
      {
        "param": "57",
        "name": "hdmi-7"
      },
      {
        "param": "00",
        "name": "video1"
      },
      {
        "param": "01",
        "name": "video2"
      },
      {
        "param": "02",
        "name": "video3"
      },
      {
        "param": "03",
        "name": "video4"
      },
      {
        "param": "04",
        "name": "video5"
      },
      {
        "param": "05",
        "name": "video6"
      },
      {
        "param": "06",
        "name": "video7"
      },
      {
        "param": "07",
        "name": "07"
      },
      {
        "param": "2A",
        "name": "usb"
      },
      {
        "param": "2B",
        "name": "network"
      },
      {
        "param": "2C",
        "name": "usb"
      },
      {
        "param": "2D",
        "name": "aiplay"
      },
      {
        "param": "2E",
        "name": "bluetooth"
      },
      {
        "param": "2F",
        "name": "usb-dac-in"
      },
      {
        "param": "UP",
        "name": "up"
      },
      {
        "param": "DOWN",
        "name": "down"
      }
    ],
    "hasQuery": true,
    "hasUpDown": true
  },
  {
    "code": "LMD",
    "name": "listening-mode",
    "description": "Listening Mode Command",
    "category": "Input / Mode",
    "actionType": "selector",
    "values": [
      {
        "param": "08",
        "name": "orchestra"
      },
      {
        "param": "09",
        "name": "unplugged"
      },
      {
        "param": "11",
        "name": "pure-audio"
      },
      {
        "param": "12",
        "name": "multiplex"
      },
      {
        "param": "13",
        "name": "full-mono"
      },
      {
        "param": "14",
        "name": "dolby-virtual"
      },
      {
        "param": "15",
        "name": "dts-surround-sensation"
      },
      {
        "param": "16",
        "name": "audyssey-dsx"
      },
      {
        "param": "23",
        "name": "stage"
      },
      {
        "param": "25",
        "name": "action"
      },
      {
        "param": "26",
        "name": "music"
      },
      {
        "param": "40",
        "name": "straight-decode"
      },
      {
        "param": "41",
        "name": "dolby-ex"
      },
      {
        "param": "42",
        "name": "thx-cinema"
      },
      {
        "param": "43",
        "name": "thx-surround-ex"
      },
      {
        "param": "44",
        "name": "thx-music"
      },
      {
        "param": "45",
        "name": "thx-games"
      },
      {
        "param": "50",
        "name": "thx-u2"
      },
      {
        "param": "51",
        "name": "thx-musicmode"
      },
      {
        "param": "52",
        "name": "thx-games"
      },
      {
        "param": "80",
        "name": "plii"
      },
      {
        "param": "81",
        "name": "plii"
      },
      {
        "param": "82",
        "name": "neo-6-cinema"
      },
      {
        "param": "83",
        "name": "neo-6-music"
      },
      {
        "param": "84",
        "name": "plii"
      },
      {
        "param": "85",
        "name": "neo-6"
      },
      {
        "param": "86",
        "name": "plii"
      },
      {
        "param": "87",
        "name": "neural-surr"
      },
      {
        "param": "88",
        "name": "neural-thx"
      },
      {
        "param": "89",
        "name": "plii"
      },
      {
        "param": "90",
        "name": "pliiz-height"
      },
      {
        "param": "91",
        "name": "neo-6-cinema-dts-surround-sensation"
      },
      {
        "param": "92",
        "name": "neo-6-music-dts-surround-sensation"
      },
      {
        "param": "93",
        "name": "neural-digital-music"
      },
      {
        "param": "94",
        "name": "pliiz-height-thx-cinema"
      },
      {
        "param": "95",
        "name": "pliiz-height-thx-music"
      },
      {
        "param": "96",
        "name": "pliiz-height-thx-games"
      },
      {
        "param": "97",
        "name": "pliiz-height-thx-u2"
      },
      {
        "param": "98",
        "name": "pliiz-height-thx-u2"
      },
      {
        "param": "99",
        "name": "pliiz-height-thx-u2"
      },
      {
        "param": "00",
        "name": "stereo"
      },
      {
        "param": "01",
        "name": "direct"
      },
      {
        "param": "02",
        "name": "surround"
      },
      {
        "param": "03",
        "name": "film"
      },
      {
        "param": "04",
        "name": "thx"
      },
      {
        "param": "05",
        "name": "action"
      },
      {
        "param": "06",
        "name": "musical"
      },
      {
        "param": "07",
        "name": "mono-movie"
      },
      {
        "param": "0A",
        "name": "studio-mix"
      },
      {
        "param": "0B",
        "name": "tv-logic"
      },
      {
        "param": "0C",
        "name": "all-ch-stereo"
      },
      {
        "param": "0D",
        "name": "theater-dimensional"
      },
      {
        "param": "0E",
        "name": "enhanced-7"
      },
      {
        "param": "0F",
        "name": "mono"
      },
      {
        "param": "1F",
        "name": "whole-house"
      },
      {
        "param": "2E",
        "name": "sports"
      },
      {
        "param": "8A",
        "name": "neo-6"
      },
      {
        "param": "8B",
        "name": "plii"
      },
      {
        "param": "8C",
        "name": "neo-6"
      },
      {
        "param": "8D",
        "name": "neural-thx-cinema"
      },
      {
        "param": "8E",
        "name": "neural-thx-music"
      },
      {
        "param": "8F",
        "name": "neural-thx-games"
      },
      {
        "param": "9A",
        "name": "neo-x-game"
      },
      {
        "param": "A0",
        "name": "pliix"
      },
      {
        "param": "A1",
        "name": "pliix"
      },
      {
        "param": "A2",
        "name": "pliix"
      },
      {
        "param": "A3",
        "name": "neo-6-cinema-audyssey-dsx"
      },
      {
        "param": "A4",
        "name": "neo-6-music-audyssey-dsx"
      },
      {
        "param": "A5",
        "name": "neural-surround-audyssey-dsx"
      },
      {
        "param": "A6",
        "name": "neural-digital-music-audyssey-dsx"
      },
      {
        "param": "A7",
        "name": "dolby-ex-audyssey-dsx"
      },
      {
        "param": "FF",
        "name": "auto-surround"
      },
      {
        "param": "UP",
        "name": "up"
      },
      {
        "param": "DOWN",
        "name": "down"
      },
      {
        "param": "MOVIE",
        "name": "movie"
      },
      {
        "param": "MUSIC",
        "name": "music"
      },
      {
        "param": "GAME",
        "name": "game"
      },
      {
        "param": "THX",
        "name": "thx"
      },
      {
        "param": "AUTO",
        "name": "auto"
      },
      {
        "param": "SURR",
        "name": "surr"
      },
      {
        "param": "STEREO",
        "name": "ster"
      }
    ],
    "hasQuery": true,
    "hasUpDown": true
  },
  {
    "code": "DIM",
    "name": "dimmer-level",
    "description": "Dimmer Level Command",
    "category": "Display / Video",
    "actionType": "selector",
    "values": [
      {
        "param": "08",
        "name": "bright-led-off"
      },
      {
        "param": "00",
        "name": "bright"
      },
      {
        "param": "01",
        "name": "dim"
      },
      {
        "param": "02",
        "name": "dark"
      },
      {
        "param": "03",
        "name": "shut-off"
      },
      {
        "param": "DIM",
        "name": "dim"
      }
    ],
    "hasQuery": true,
    "hasUpDown": false
  },
  {
    "code": "HDO",
    "name": "hdmi-output-selector",
    "description": "HDMI Output Selector",
    "category": "Display / Video",
    "actionType": "selector",
    "values": [
      {
        "param": "00",
        "name": "no"
      },
      {
        "param": "01",
        "name": "yes"
      },
      {
        "param": "02",
        "name": "out-sub"
      },
      {
        "param": "03",
        "name": "both"
      },
      {
        "param": "04",
        "name": "both"
      },
      {
        "param": "05",
        "name": "both"
      },
      {
        "param": "UP",
        "name": "up"
      }
    ],
    "hasQuery": true,
    "hasUpDown": true
  },
  {
    "code": "SPA",
    "name": "speaker-a",
    "description": "Speaker A Command",
    "category": "Speaker",
    "actionType": "selector",
    "values": [
      {
        "param": "00",
        "name": "off"
      },
      {
        "param": "01",
        "name": "on"
      },
      {
        "param": "UP",
        "name": "up"
      }
    ],
    "hasQuery": true,
    "hasUpDown": true
  },
  {
    "code": "SPB",
    "name": "speaker-b",
    "description": "Speaker B Command",
    "category": "Speaker",
    "actionType": "selector",
    "values": [
      {
        "param": "00",
        "name": "off"
      },
      {
        "param": "01",
        "name": "on"
      },
      {
        "param": "UP",
        "name": "up"
      }
    ],
    "hasQuery": true,
    "hasUpDown": true
  },
  {
    "code": "DIR",
    "name": "direct",
    "description": "Direct Command",
    "category": "Audio Processing",
    "actionType": "toggle",
    "values": [
      {
        "param": "00",
        "name": "off"
      },
      {
        "param": "01",
        "name": "on"
      },
      {
        "param": "TG",
        "name": "toggle"
      }
    ],
    "hasQuery": true,
    "hasUpDown": false,
    "onValue": "01",
    "offValue": "00",
    "toggleValue": "TG"
  },
  {
    "code": "LTN",
    "name": "late-night",
    "description": "Late Night Command",
    "category": "Audio Processing",
    "actionType": "selector",
    "values": [
      {
        "param": "00",
        "name": "off"
      },
      {
        "param": "01",
        "name": "low-dolbydigital"
      },
      {
        "param": "02",
        "name": "high-dolbydigital"
      },
      {
        "param": "03",
        "name": "auto-dolby-truehd"
      },
      {
        "param": "UP",
        "name": "up"
      }
    ],
    "hasQuery": true,
    "hasUpDown": true
  },
  {
    "code": "RAS",
    "name": "cinema-filter",
    "description": "Cinema Filter Command",
    "category": "Audio Processing",
    "actionType": "selector",
    "values": [
      {
        "param": "00",
        "name": "off"
      },
      {
        "param": "01",
        "name": "on"
      },
      {
        "param": "UP",
        "name": "up"
      }
    ],
    "hasQuery": true,
    "hasUpDown": true
  },
  {
    "code": "CTL",
    "name": "center-temporary-level",
    "description": "Center (temporary) Level Command",
    "category": "Volume",
    "actionType": "stepper",
    "values": [
      {
        "param": "UP",
        "name": "up"
      },
      {
        "param": "DOWN",
        "name": "down"
      }
    ],
    "hasQuery": true,
    "hasUpDown": true
  },
  {
    "code": "ADY",
    "name": "audyssey-2eq-multeq-multeq-xt",
    "description": "Audyssey 2EQ/MultEQ/MultEQ XT",
    "category": "Audio Processing",
    "actionType": "selector",
    "values": [
      {
        "param": "00",
        "name": "off"
      },
      {
        "param": "01",
        "name": "on"
      },
      {
        "param": "02",
        "name": "music"
      },
      {
        "param": "UP",
        "name": "up"
      }
    ],
    "hasQuery": true,
    "hasUpDown": true
  },
  {
    "code": "ADQ",
    "name": "audyssey-dynamic-eq",
    "description": "Audyssey Dynamic EQ",
    "category": "Audio Processing",
    "actionType": "selector",
    "values": [
      {
        "param": "00",
        "name": "off"
      },
      {
        "param": "01",
        "name": "on"
      },
      {
        "param": "UP",
        "name": "up"
      }
    ],
    "hasQuery": true,
    "hasUpDown": true
  },
  {
    "code": "PMB",
    "name": "phase-matching-bass",
    "description": "Phase Matching Bass Command",
    "category": "Audio Processing",
    "actionType": "toggle",
    "values": [
      {
        "param": "00",
        "name": "off"
      },
      {
        "param": "01",
        "name": "on"
      },
      {
        "param": "TG",
        "name": "toggle"
      }
    ],
    "hasQuery": true,
    "hasUpDown": false,
    "onValue": "01",
    "offValue": "00",
    "toggleValue": "TG"
  },
  {
    "code": "TFR",
    "name": "tone-front",
    "description": "Tone(Front) Command",
    "category": "Tone",
    "actionType": "selector",
    "values": [
      {
        "param": "BUP",
        "name": "bass-up"
      },
      {
        "param": "BDOWN",
        "name": "bass-down"
      },
      {
        "param": "TUP",
        "name": "treble-up"
      },
      {
        "param": "TDOWN",
        "name": "treble-down"
      }
    ],
    "hasQuery": true,
    "hasUpDown": false
  },
  {
    "code": "PRS",
    "name": "preset",
    "description": "Preset Command (Include Tuner Pack Model Only)",
    "category": "Tuner",
    "actionType": "stepper",
    "values": [
      {
        "param": "UP",
        "name": "up"
      },
      {
        "param": "DOWN",
        "name": "down"
      }
    ],
    "hasQuery": true,
    "hasUpDown": true
  },
  {
    "code": "NTC",
    "name": "network-usb",
    "description": "Network/USB Operation Command (Network Model Only after TX-NR905)",
    "category": "Transport",
    "actionType": "selector",
    "values": [
      {
        "param": "0",
        "name": "0"
      },
      {
        "param": "1",
        "name": "1"
      },
      {
        "param": "2",
        "name": "2"
      },
      {
        "param": "3",
        "name": "3"
      },
      {
        "param": "4",
        "name": "4"
      },
      {
        "param": "5",
        "name": "5"
      },
      {
        "param": "6",
        "name": "6"
      },
      {
        "param": "7",
        "name": "7"
      },
      {
        "param": "8",
        "name": "8"
      },
      {
        "param": "9",
        "name": "9"
      },
      {
        "param": "PLAY",
        "name": "play"
      },
      {
        "param": "STOP",
        "name": "stop"
      },
      {
        "param": "PAUSE",
        "name": "pause"
      },
      {
        "param": "P/P",
        "name": "p-p"
      },
      {
        "param": "TRUP",
        "name": "trup"
      },
      {
        "param": "TRDN",
        "name": "trdn"
      },
      {
        "param": "FF",
        "name": "ff"
      },
      {
        "param": "REW",
        "name": "rew"
      },
      {
        "param": "REPEAT",
        "name": "repeat"
      },
      {
        "param": "RANDOM",
        "name": "random"
      },
      {
        "param": "REP/SHF",
        "name": "rep-shf"
      },
      {
        "param": "DISPLAY",
        "name": "display"
      },
      {
        "param": "ALBUM",
        "name": "album"
      },
      {
        "param": "ARTIST",
        "name": "artist"
      },
      {
        "param": "GENRE",
        "name": "genre"
      },
      {
        "param": "PLAYLIST",
        "name": "playlist"
      },
      {
        "param": "RIGHT",
        "name": "right"
      },
      {
        "param": "LEFT",
        "name": "left"
      },
      {
        "param": "UP",
        "name": "up"
      },
      {
        "param": "DOWN",
        "name": "down"
      },
      {
        "param": "SELECT",
        "name": "select"
      },
      {
        "param": "DELETE",
        "name": "delete"
      },
      {
        "param": "CAPS",
        "name": "caps"
      },
      {
        "param": "LOCATION",
        "name": "location"
      },
      {
        "param": "LANGUAGE",
        "name": "language"
      },
      {
        "param": "SETUP",
        "name": "setup"
      },
      {
        "param": "RETURN",
        "name": "return"
      },
      {
        "param": "CHUP",
        "name": "chup"
      },
      {
        "param": "CHDN",
        "name": "chdn"
      },
      {
        "param": "MENU",
        "name": "menu"
      },
      {
        "param": "TOP",
        "name": "top"
      },
      {
        "param": "MODE",
        "name": "mode"
      },
      {
        "param": "LIST",
        "name": "list"
      },
      {
        "param": "MEMORY",
        "name": "memory"
      },
      {
        "param": "F1",
        "name": "f1"
      },
      {
        "param": "F2",
        "name": "f2"
      }
    ],
    "hasQuery": false,
    "hasUpDown": true
  },
  {
    "code": "ZPW",
    "name": "power",
    "description": "Zone2 Power Command",
    "category": "Zone 2",
    "actionType": "toggle",
    "values": [
      {
        "param": "00",
        "name": "standby"
      },
      {
        "param": "01",
        "name": "on"
      }
    ],
    "hasQuery": true,
    "hasUpDown": false,
    "onValue": "01",
    "offValue": "00"
  },
  {
    "code": "ZMT",
    "name": "muting",
    "description": "Zone2 Muting Command",
    "category": "Zone 2",
    "actionType": "toggle",
    "values": [
      {
        "param": "00",
        "name": "off"
      },
      {
        "param": "01",
        "name": "on"
      },
      {
        "param": "TG",
        "name": "toggle"
      }
    ],
    "hasQuery": true,
    "hasUpDown": false,
    "onValue": "01",
    "offValue": "00",
    "toggleValue": "TG"
  },
  {
    "code": "ZVL",
    "name": "volume",
    "description": "Zone2 Volume Command",
    "category": "Zone 2",
    "actionType": "stepper",
    "values": [
      {
        "param": "UP",
        "name": "level-up"
      },
      {
        "param": "DOWN",
        "name": "level-down"
      },
      {
        "param": "UP1",
        "name": "level-up-1db-step"
      },
      {
        "param": "DOWN1",
        "name": "level-down-1db-step"
      }
    ],
    "hasQuery": true,
    "hasUpDown": true
  },
  {
    "code": "SLZ",
    "name": "selector",
    "description": "ZONE2 Selector Command",
    "category": "Zone 2",
    "actionType": "selector",
    "values": [
      {
        "param": "08",
        "name": "hidden2"
      },
      {
        "param": "09",
        "name": "hidden3"
      },
      {
        "param": "10",
        "name": "dvd"
      },
      {
        "param": "11",
        "name": "strm-box"
      },
      {
        "param": "12",
        "name": "tv"
      },
      {
        "param": "20",
        "name": "tape"
      },
      {
        "param": "21",
        "name": "tape2"
      },
      {
        "param": "22",
        "name": "phono"
      },
      {
        "param": "23",
        "name": "cd"
      },
      {
        "param": "24",
        "name": "fm"
      },
      {
        "param": "25",
        "name": "am"
      },
      {
        "param": "26",
        "name": "tuner"
      },
      {
        "param": "27",
        "name": "music-server"
      },
      {
        "param": "28",
        "name": "internet-radio"
      },
      {
        "param": "29",
        "name": "usb"
      },
      {
        "param": "30",
        "name": "multi-ch"
      },
      {
        "param": "31",
        "name": "xm"
      },
      {
        "param": "32",
        "name": "sirius"
      },
      {
        "param": "33",
        "name": "dab"
      },
      {
        "param": "40",
        "name": "universal-port"
      },
      {
        "param": "55",
        "name": "hdmi-5"
      },
      {
        "param": "56",
        "name": "hdmi-6"
      },
      {
        "param": "57",
        "name": "hdmi-7"
      },
      {
        "param": "80",
        "name": "source"
      },
      {
        "param": "00",
        "name": "video1"
      },
      {
        "param": "01",
        "name": "video2"
      },
      {
        "param": "02",
        "name": "video3"
      },
      {
        "param": "03",
        "name": "video4"
      },
      {
        "param": "04",
        "name": "video5"
      },
      {
        "param": "05",
        "name": "video6"
      },
      {
        "param": "06",
        "name": "video7"
      },
      {
        "param": "07",
        "name": "hidden1"
      },
      {
        "param": "2A",
        "name": "usb"
      },
      {
        "param": "2B",
        "name": "network"
      },
      {
        "param": "2C",
        "name": "usb"
      },
      {
        "param": "2D",
        "name": "airplay"
      },
      {
        "param": "2E",
        "name": "bluetooth"
      },
      {
        "param": "7F",
        "name": "off"
      },
      {
        "param": "UP",
        "name": "up"
      },
      {
        "param": "DOWN",
        "name": "down"
      }
    ],
    "hasQuery": true,
    "hasUpDown": true
  }
];
